// Auto-generated by: pnpm --filter @synap/db generate-types
// Run after: supabase db push

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type MemoryCategory = 'personal' | 'preferences' | 'professional' | 'custom'
export type MessageRole = 'user' | 'assistant' | 'system'

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          display_name: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          display_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          display_name?: string | null
          avatar_url?: string | null
          updated_at?: string
        }
      }
      memory_facts: {
        Row: {
          id: string
          user_id: string
          category: MemoryCategory
          key: string
          value: string
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          category?: MemoryCategory
          key: string
          value: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          category?: MemoryCategory
          key?: string
          value?: string
          is_active?: boolean
          updated_at?: string
        }
      }
      conversations: {
        Row: {
          id: string
          user_id: string
          title: string | null
          current_ai: string
          memory_injected: boolean
          last_message_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title?: string | null
          current_ai: string
          memory_injected?: boolean
          last_message_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          title?: string | null
          current_ai?: string
          memory_injected?: boolean
          last_message_at?: string | null
          updated_at?: string
        }
      }
      messages: {
        Row: {
          id: string
          conversation_id: string
          user_id: string
          role: MessageRole
          content: string
          ai_provider: string | null
          is_context_summary: boolean
          metadata: Json
          created_at: string
        }
        Insert: {
          id?: string
          conversation_id: string
          user_id: string
          role: MessageRole
          content: string
          ai_provider?: string | null
          is_context_summary?: boolean
          metadata?: Json
          created_at?: string
        }
        Update: {
          content?: string
          metadata?: Json
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      memory_category: MemoryCategory
      message_role: MessageRole
    }
  }
}
